sudo: required
services:
  - docker
before_install:
  - docker build -t dponnada/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dponnada/react-test npm test

after_sucess:
  - docker build -t dponnada/multi-client ./client
  - docker build -t dponnada/multi-nginx ./nignx
  - docker build -t dponnada/multi-server ./server
  - docker build -t dponnada/multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images push then in docker cli
  - docker push dponnada/multi-client
  - docker push dponnada/multi-nginx
  - docker push dponnada/multi-server
  - docker push dponnada/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-927729158917"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
